services:
  app:
    build:
      context: node
    networks:
      - nodeNetwork
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - 3000:3000
    container_name: app
    depends_on:
      - db
    command: sh -c "dockerize -wait tcp://db:3306 -timeout 30s && npm install && npm run start"
  db:
    image: mysql:latest
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
    networks:
      - nodeNetwork
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    tty: true
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - nodeNetwork

networks:
  nodeNetwork:
    driver: bridge
